version: '4'
services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    
    ports:
      - '80:3000'

      #volume mounting is a reference
    volumes:
      - .:/app
      - /app/node_modules #ensures node_modules is not mapped into the container